[package]
name = "first"
version = "0.1.0"
authors = ["Andrii Tsvielodub <andrey@zoomdata.com>"]

[dependencies]
serde = "1.0.23"
serde_derive = "1.0.23"

chrono = "0.4.0"

rocket = "0.3.3"
rocket_contrib = "0.3.3"
rocket_codegen = "0.3.3"